package com.medisanaspace.model;

import com.medisanaspace.library.RandomHelper;
import com.medisanaspace.model.base.Versionable;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

public class Glucodockmeal extends Versionable {

	public static final int MIN_CARBOHYDRATES = 80;

	public static final int MAX_CARBOHYDRATES = 230;

	private Integer carbohydrates;
	private String moduleSerialId;

	public static com.medisanaspace.model.Glucodockmeal generateRandomEntry() {
		Glucodockmeal glucodockmeal = new Glucodockmeal();
		glucodockmeal.setCarbohydrates(RandomHelper.generateInt(
				MIN_CARBOHYDRATES, MAX_CARBOHYDRATES));
		glucodockmeal.setModuleSerialId("[Autogenerated item]");
		return glucodockmeal;
	}

	public String getModuleSerialId() {
		return this.moduleSerialId;
	}

	public void setModuleSerialId(String moduleSerialId) {
		this.moduleSerialId = moduleSerialId;
	}

	public Integer getCarbohydrates() {
		return this.carbohydrates;
	}

	public void setCarbohydrates(Integer carbohydrates) {
		this.carbohydrates = carbohydrates;
	}

	public String toJson() {
		return new JSONSerializer().exclude("*.class").serialize(this);
	}

	public static Glucodockmeal fromJsonToGlucodockmeal(String json) {
		return new JSONDeserializer<Glucodockmeal>().use(null,
				Glucodockmeal.class).deserialize(json);
	}

	public static String toJsonArray(Collection<Glucodockmeal> collection) {
		return new JSONSerializer().exclude("*.class").exclude("active")
				.exclude("updatedDate").exclude("version")
				.serialize(collection);
	}

	public static Collection<Glucodockmeal> fromJsonArrayToGlucodockmeals(
			String json) {
		return new JSONDeserializer<List<Glucodockmeal>>()
				.use(null, ArrayList.class).use("values", Glucodockmeal.class)
				.deserialize(json);
	}
}
