package com.medisanaspace.model;

import com.medisanaspace.library.RandomHelper;
import com.medisanaspace.model.base.BaseModel;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 */
public class Glucodockglucose extends BaseModel {

	public static final int MIN_BLOOD_GLUCOSE = 40;

	public static final int MAX_BLOOD_GLUCOSE = 250;

	public static final int MIN_BLOOD_GLUCOSE_TARGET_MIN = 80;

	public static final int MAX_BLOOD_GLUCOSE_TARGET_MIN = 140;

	public static final int MIN_BLOOD_GLUCOSE_TARGET_MAX = 40;

	public static final int MAX_BLOOD_GLUCOSE_TARGET_MAX = 250;

	private Integer bloodGlucose;
	private Integer bloodGlucoseTargetMin;
	private Integer bloodGlucoseTargetMax;
	private String moduleSerialId;

	/**
	 * Method generateRandomEntry.
	 * @return Glucodockglucose
	 */
	public static final Glucodockglucose generateRandomEntry() {
		final Glucodockglucose glucodockglucose = new Glucodockglucose();
		glucodockglucose.setBloodGlucose(RandomHelper.generateInt(
				MIN_BLOOD_GLUCOSE, MAX_BLOOD_GLUCOSE));
		glucodockglucose.setBloodGlucoseTargetMin(RandomHelper.generateInt(
				MIN_BLOOD_GLUCOSE_TARGET_MIN, MAX_BLOOD_GLUCOSE_TARGET_MIN));
		glucodockglucose.setBloodGlucoseTargetMax(RandomHelper.generateInt(
				MIN_BLOOD_GLUCOSE_TARGET_MAX, MAX_BLOOD_GLUCOSE_TARGET_MAX));
		glucodockglucose.setMealStatus(RandomHelper.generateInt(
				MIN_MEAL_STATUS, MAX_MEAL_STATUS));
		glucodockglucose.setActivityStatus(RandomHelper.generateInt(
				MIN_ACTIVITY_STATUS, MAX_ACTIVITY_STATUS));
		glucodockglucose.setMood(RandomHelper.generateInt(MIN_MOOD, MAX_MOOD));
		glucodockglucose.setNote("[Autogenerated item]");
		glucodockglucose.setModuleSerialId("[Autogenerated item]");
		return glucodockglucose;
	}

	/**
	 * Method getBloodGlucose.
	 * @return Integer
	 */
	public final Integer getBloodGlucose() {
		return this.bloodGlucose;
	}

	/**
	 * Method setBloodGlucose.
	 * @param bloodGlucose Integer
	 */
	public void setBloodGlucose(final Integer bloodGlucose) {
		this.bloodGlucose = bloodGlucose;
	}

	/**
	 * Method getBloodGlucoseTargetMin.
	 * @return Integer
	 */
	public final Integer getBloodGlucoseTargetMin() {
		return this.bloodGlucoseTargetMin;
	}

	/**
	 * Method setBloodGlucoseTargetMin.
	 * @param bloodGlucoseTargetMin Integer
	 */
	public void setBloodGlucoseTargetMin(final Integer bloodGlucoseTargetMin) {
		this.bloodGlucoseTargetMin = bloodGlucoseTargetMin;
	}

	/**
	 * Method getBloodGlucoseTargetMax.
	 * @return Integer
	 */
	public final Integer getBloodGlucoseTargetMax() {
		return this.bloodGlucoseTargetMax;
	}

	/**
	 * Method setBloodGlucoseTargetMax.
	 * @param bloodGlucoseTargetMax Integer
	 */
	public void setBloodGlucoseTargetMax(final Integer bloodGlucoseTargetMax) {
		this.bloodGlucoseTargetMax = bloodGlucoseTargetMax;
	}

	/**
	 * Method toJson.
	 * @return String
	 */
	public final String toJson() {
		return new JSONSerializer().exclude("*.class").serialize(this);
	}

	/**
	 * Method fromJsonToGlucodockglucose.
	 * @param json String
	 * @return Glucodockglucose
	 */
	public static final Glucodockglucose fromJsonToGlucodockglucose(
			final String json) {
		return new JSONDeserializer<Glucodockglucose>().use(null,
				Glucodockglucose.class).deserialize(json);
	}

	/**
	 * Method toJsonArray.
	 * @param collection Collection<Glucodockglucose>
	 * @return String
	 */
	public static final String toJsonArray(
			final Collection<Glucodockglucose> collection) {
		return new JSONSerializer().exclude("*.class").exclude("active")
				.exclude("updatedDate").exclude("version").exclude("id")
				.serialize(collection);
	}

	/**
	 * Method fromJsonArrayToGlucodockglucoses.
	 * @param json String
	 * @return Collection<Glucodockglucose>
	 */
	public static final Collection<Glucodockglucose> fromJsonArrayToGlucodockglucoses(
			final String json) {
		return new JSONDeserializer<List<Glucodockglucose>>()
				.use(null, ArrayList.class)
				.use("values", Glucodockglucose.class).deserialize(json);
	}

	/**
	 * Method getModuleSerialId.
	 * @return String
	 */
	public final String getModuleSerialId() {
		return this.moduleSerialId;
	}

	/**
	 * Method setModuleSerialId.
	 * @param moduleSerialId String
	 */
	public void setModuleSerialId(final String moduleSerialId) {
		this.moduleSerialId = moduleSerialId;
	}
}
