// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.medisanaspace.model;

import com.medisanaspace.model.base.Versionable;

/**
 */
public class TrackerStats extends Versionable {

	private Float calories;
	private Integer steps;
	private Integer runningSteps;
	private Float distance;
	private Integer durationActivity;
	private Integer durationSleep;
	private Integer sleepQuality;

	/**
	 * Method getCalories.
	 * @return Float
	 */
	public Float getCalories() {
		return calories;
	}

	/**
	 * Method setCalories.
	 * @param calories Float
	 */
	public void setCalories(Float calories) {
		this.calories = calories;
	}

	/**
	 * Method getSteps.
	 * @return Integer
	 */
	public Integer getSteps() {
		return steps;
	}

	/**
	 * Method setSteps.
	 * @param steps Integer
	 */
	public void setSteps(Integer steps) {
		this.steps = steps;
	}

	/**
	 * Method getRunningSteps.
	 * @return Integer
	 */
	public Integer getRunningSteps() {
		return runningSteps;
	}

	/**
	 * Method setRunningSteps.
	 * @param runningSteps Integer
	 */
	public void setRunningSteps(Integer runningSteps) {
		this.runningSteps = runningSteps;
	}

	/**
	 * Method getDistance.
	 * @return Float
	 */
	public Float getDistance() {
		return distance;
	}

	/**
	 * Method setDistance.
	 * @param distance Float
	 */
	public void setDistance(Float distance) {
		this.distance = distance;
	}

	/**
	 * Method getDurationActivity.
	 * @return Integer
	 */
	public Integer getDurationActivity() {
		return durationActivity;
	}

	/**
	 * Method setDurationActivity.
	 * @param durationActivity Integer
	 */
	public void setDurationActivity(Integer durationActivity) {
		this.durationActivity = durationActivity;
	}

	/**
	 * Method getDurationSleep.
	 * @return Integer
	 */
	public Integer getDurationSleep() {
		return durationSleep;
	}

	/**
	 * Method setDurationSleep.
	 * @param durationSleep Integer
	 */
	public void setDurationSleep(Integer durationSleep) {
		this.durationSleep = durationSleep;
	}

	/**
	 * Method getSleepQuality.
	 * @return Integer
	 */
	public Integer getSleepQuality() {
		return sleepQuality;
	}

	/**
	 * Method setSleepQuality.
	 * @param sleepQuality Integer
	 */
	public void setSleepQuality(Integer sleepQuality) {
		this.sleepQuality = sleepQuality;
	}

}
