package com.medisanaspace.model;

import com.medisanaspace.library.RandomHelper;
import com.medisanaspace.model.base.Versionable;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 */
public class Glucodockinsulin extends Versionable {

	public static final int MIN_INSULIN = 30;

	public static final int MAX_INSULIN = 80;

	public static final int MIN_INSULIN_TYPE_INDEX = 0;

	public static final int MAX_INSULIN_TYPE_INDEX = 2;

	public static final int MAX_INSULIN_TYPE_NAME_LENGTH = 512;

	private Float insulin;
	private Integer insulinTypeIndex;
	private String insulinTypeName;
	private String moduleSerialId;
	private String insulinTypeName2;
	private String insulinTypeName3;

	/**
	 * Method generateRandomEntry.
	 * @return com.medisanaspace.model.Glucodockinsulin
	 */
	public static com.medisanaspace.model.Glucodockinsulin generateRandomEntry() {
		final Glucodockinsulin glucodockinsulin = new Glucodockinsulin();
		glucodockinsulin.setInsulin(RandomHelper.generateFloat(MIN_INSULIN,
				MAX_INSULIN));
		glucodockinsulin.setInsulinTypeIndex(RandomHelper.generateInt(
				MIN_INSULIN_TYPE_INDEX, MAX_INSULIN_TYPE_INDEX));
		glucodockinsulin.setInsulinTypeName("[Autogenerated item]");
		glucodockinsulin.setModuleSerialId("[Autogenerated item]");
		return glucodockinsulin;
	}

	/**
	 * Method toJson.
	 * @return String
	 */
	public String toJson() {
		return new JSONSerializer().exclude("*.class").serialize(this);
	}

	/**
	 * Method fromJsonToGlucodockinsulin.
	 * @param json String
	 * @return Glucodockinsulin
	 */
	public static Glucodockinsulin fromJsonToGlucodockinsulin(final String json) {
		return new JSONDeserializer<Glucodockinsulin>().use(null,
				Glucodockinsulin.class).deserialize(json);
	}

	/**
	 * Method toJsonArray.
	 * @param collection Collection<Glucodockinsulin>
	 * @return String
	 */
	public static String toJsonArray(
			final Collection<Glucodockinsulin> collection) {
		return new JSONSerializer().exclude("*.class").exclude("active")
				.exclude("updatedDate").exclude("version").exclude("id")
				.serialize(collection);
	}

	/**
	 * Method fromJsonArrayToGlucodockinsulins.
	 * @param json String
	 * @return Collection<Glucodockinsulin>
	 */
	public static Collection<Glucodockinsulin> fromJsonArrayToGlucodockinsulins(
			final String json) {
		return new JSONDeserializer<List<Glucodockinsulin>>()
				.use(null, ArrayList.class)
				.use("values", Glucodockinsulin.class).deserialize(json);
	}

	/**
	 * Method getModuleSerialId.
	 * @return String
	 */
	public final String getModuleSerialId() {
		return this.moduleSerialId;
	}

	/**
	 * Method setModuleSerialId.
	 * @param moduleSerialId String
	 */
	public void setModuleSerialId(final String moduleSerialId) {
		this.moduleSerialId = moduleSerialId;
	}

	/**
	 * Method getInsulinTypeName2.
	 * @return String
	 */
	public final String getInsulinTypeName2() {
		return this.insulinTypeName2;
	}

	/**
	 * Method setInsulinTypeName2.
	 * @param insulinTypeName2 String
	 */
	public void setInsulinTypeName2(final String insulinTypeName2) {
		this.insulinTypeName2 = insulinTypeName2;
	}

	/**
	 * Method getInsulinTypeName3.
	 * @return String
	 */
	public final String getInsulinTypeName3() {
		return this.insulinTypeName3;
	}

	/**
	 * Method setInsulinTypeName3.
	 * @param insulinTypeName3 String
	 */
	public void setInsulinTypeName3(final String insulinTypeName3) {
		this.insulinTypeName3 = insulinTypeName3;
	}

	/**
	 * Method getInsulin.
	 * @return Float
	 */
	public final Float getInsulin() {
		return this.insulin;
	}

	/**
	 * Method setInsulin.
	 * @param insulin Float
	 */
	public void setInsulin(final Float insulin) {
		this.insulin = insulin;
	}

	/**
	 * Method getInsulinTypeIndex.
	 * @return Integer
	 */
	public final Integer getInsulinTypeIndex() {
		return this.insulinTypeIndex;
	}

	/**
	 * Method setInsulinTypeIndex.
	 * @param insulinTypeIndex Integer
	 */
	public void setInsulinTypeIndex(final Integer insulinTypeIndex) {
		this.insulinTypeIndex = insulinTypeIndex;
	}

	/**
	 * Method getInsulinTypeName.
	 * @return String
	 */
	public final String getInsulinTypeName() {
		return this.insulinTypeName;
	}

	/**
	 * Method setInsulinTypeName.
	 * @param insulinTypeName String
	 */
	public void setInsulinTypeName(final String insulinTypeName) {
		this.insulinTypeName = insulinTypeName;
	}
}
