package com.medisanaspace.model;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

import com.medisanaspace.model.base.Versionable;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;

/**
 */
public class Order extends Versionable {

	private String email;
	private String phoneNumber;
	private String firstName;
	private String lastName;
	private String address;
	private String code;
	private String city;
	private String state;
	private String country;
	private String type;
	private String note;

	private String moduleSerialId;

	/**
	 * Method generateRandomEntry.
	 * @return Order
	 */
	public static Order generateRandomEntry() {
		final Order order = new Order();

		order.setEmail("test@mail.de");
		order.setPhoneNumber("1234 567890");
		order.setFirstName("Vorname");
		order.setLastName("Nachname");
		order.setAddress("Adressenweg 1");
		order.setCode("12345");
		order.setCity("Teststadt");
		order.setState("Testbundesland");
		order.setCountry("Testland");
		order.setType("2c2a4ed3-3782-49cf-96c4-bb8b7c9c20b3");
		order.setNote("manual test - Einmalige Test-E-Mail zum Test der E-Mail-Weiterleitung, bitte ignorieren, danke!");

		order.setModuleSerialId("[Autogenerated module serial id]");
		order.setMeasurementDate(new Date());

		return order;
	}

	/**
	 * Method toJson.
	 * @return String
	 */
	public final String toJson() {
		return new JSONSerializer().exclude("*.class").serialize(this);
	}

	/**
	 * Method fromJsonToOrder.
	 * @param json String
	 * @return Order
	 */
	public static final Order fromJsonToOrder(final String json) {
		return new JSONDeserializer<Order>().use(null, Order.class)
				.deserialize(json);
	}

	/**
	 * Method toJsonArray.
	 * @param collection Collection<Order>
	 * @return String
	 */
	public static final String toJsonArray(final Collection<Order> collection) {
		return new JSONSerializer().exclude("*.class").exclude("active")
				.exclude("updatedDate").exclude("version").exclude("id")
				.serialize(collection);
	}

	/**
	 * Method fromJsonArrayToTargetscales.
	 * @param json String
	 * @return Collection<Order>
	 */
	public static final Collection<Order> fromJsonArrayToTargetscales(
			final String json) {
		return new JSONDeserializer<List<Order>>().use(null, ArrayList.class)
				.use("values", Order.class).deserialize(json);
	}

	/**
	 * Method getModuleSerialId.
	 * @return String
	 */
	public final String getModuleSerialId() {
		return this.moduleSerialId;
	}

	/**
	 * Method setModuleSerialId.
	 * @param moduleSerialId String
	 */
	public void setModuleSerialId(final String moduleSerialId) {
		this.moduleSerialId = moduleSerialId;
	}

	/**
	 * Method getEmail.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * Method setEmail.
	 * @param email String
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Method getPhoneNumber.
	 * @return String
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * Method setPhoneNumber.
	 * @param phoneNumber String
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/**
	 * Method getFirstName.
	 * @return String
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * Method setFirstName.
	 * @param firstName String
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * Method getLastName.
	 * @return String
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * Method setLastName.
	 * @param lastName String
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * Method getAddress.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * Method setAddress.
	 * @param address String
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * Method getCode.
	 * @return String
	 */
	public String getCode() {
		return code;
	}

	/**
	 * Method setCode.
	 * @param code String
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * Method getCity.
	 * @return String
	 */
	public String getCity() {
		return city;
	}

	/**
	 * Method setCity.
	 * @param city String
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * Method getState.
	 * @return String
	 */
	public String getState() {
		return state;
	}

	/**
	 * Method setState.
	 * @param state String
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * Method getCountry.
	 * @return String
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * Method setCountry.
	 * @param country String
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * Method getType.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/**
	 * Method setType.
	 * @param type String
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Method getNote.
	 * @return String
	 */
	public String getNote() {
		return note;
	}

	/**
	 * Method setNote.
	 * @param note String
	 */
	public void setNote(String note) {
		this.note = note;
	}

}
